### ISSUE TITLE
[BUG] The request handler doesn't respect the type of the input as specified in the swagger.

### ISSUE THREAD

**Issue by jonmanga** [acrontum/generate-it#32]
**Describe the bug**
The request handler automatically converts a csv string to an array. It, therefore, breaks validation because the validator and the domain still expects a string. Conversely, when given a single value it assumes it's a string and doesn't convert it to a single value array. Therefore, also failing validation and Domain.

**To Reproduce**
1. Define a path with a query parameter that takes a string.
2. Generate the backend
3. Send a request and set the query parameter to a csv i.e. `url?select=name,surname`

Steps to reproduce converse behavior:
1. Define a path with a query parameter that takes a string array.
2. Generate the backend
3. Send a request and set the query parameter to a single string  i.e. `url?select=name`

**Expected behavior**
The expected behaviour is that the request handler respects the type of the properties as specified in Swagger definitions.

Currently, in case one it will convert it to a string array and fails validation.
In case number two the input is left as is and fails validation because a string array was expected.

The workaround is to set csv to type string array and append a comma to the request query, but I'll have to filter out the null value in code.

**Comment by johndcarmichael** [comment]
@jonmanga  i believe this was added to the mix by @acrontum-revah  a looonnngg time ago as a result of java codegen. If I remember correctly the client for angular takes an array and back then mushes into a CSV style string. To get around this limitation a middleware was written to parse this content.

This issue is not with the core but with the typescript server templates.

https://github.com/acrontum/openapi-nodegen-typescript-server/blob/master/src/http/nodegen/middleware/queryArrayParserMiddleware.ts

Don't forget that the middleware importer is not regenerated after the 1st use, so you can just delete the inclusion in your local API:

https://github.com/acrontum/openapi-nodegen-typescript-server/blob/master/src/http/middlewaresImporter.ts#L28
